apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 3000  # ganti sesuai containerPort di atas
    nodePort: 30080   # optional, bisa diatur otomatis kalau dihapus
